services:
  web:
    build: .
    ports:
      - "8089:8080"
    depends_on:
      - db
    environment:
        SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    env_file:
        - .env

  db:
    image: mariadb
    ports:
      - "3366:3306"
    environment:
        MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
